database:
  type: postgres
  host: localhost
  port: 5432
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  dbname: SitesIndex
crawler:
  workers: 5
  depth: 1
  delay: "2"
  timeout: 10
  maintenance: 60
api:
  port: 8080
  host: 0.0.0.0
  timeout: 10
selenium:
  - type: chrome
    path: ""
    port: 4444
    headless: true
    host: localhost
network_info:
  dns:
    enabled: true
  whois:
    enabled: true
  httpinfo:
    enabled: true
  sslinfo:
    enabled: true
  geo_localization:
    enabled: false
    path: ""

debug_level: 1
